language: python
cache: pip
sudo: required
os: xenial

# Environment variables
env:
  TEST_QT=false

# Test environments
matrix:
  include:
   - env: TOXENV=py34
     python: 3.4
   #- env: TOXENV=py35
   #  python: 3.5
   #- env: TOXENV=py36
   #  python: 3.6

# Package installation
install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pyqt5
  - sudo apt-get install -y python3-pyqt5.qsci 
  - sudo apt-get install -y python3-pip
  - pip3 install tox codecov

# Run tests
script:
  - tox

# Register code coverage in coveralls
after_success:
  - codecov
